l_english:
 PRODUCTION_MATERIALS_OIL:0 "Oil"
 PRODUCTION_MATERIALS_MANA:0 "Mana"
 PRODUCTION_MATERIALS_WOOD:0 "Wood"
 PRODUCTION_MATERIALS_MOUNTS:0 "Mounts"
 PRODUCTION_MATERIALS_ORES:0 "Ores"
 PRODUCTION_MATERIALS_GUNPOWDER:0 "Gunpowder"
 PRODUCTION_MATERIALS_EGGS:0 "Eggs"
 PRODUCTION_MATERIALS_WHEAT:0 "Wheat"
 country_resource_mana:0 "Mana"
